---
- name: pull mini_project image
  hosts: all
  tasks:
    - name: Pull junit devops image
      docker_image:
        name: nagasrihith608/scientific-calculator-miniproject
        source: pull

    - name: running container
      shell: docker run -id nagasrihith608/scientific-calculator-miniproject
