---
- name: Pull docker image of Calculator
  hosts: ansible all --list-hosts
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Pull docker image
      shell: docker pull nagasrihith608/scientific-calculator-miniproject/calc:latest

    - name: Run container on remote host
      shell: docker run -it -d nagasrihith608/scientific-calculator-miniproject:latest /bin/bash